// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.13.0
// source: pedido/pedido.proto

package pedido

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Estatus int32

const (
	Estatus_OK        Estatus = 0
	Estatus_PERDIDO   Estatus = 1
	Estatus_EN_CAMINO Estatus = 2
	Estatus_ERROR     Estatus = 3
)

// Enum value maps for Estatus.
var (
	Estatus_name = map[int32]string{
		0: "OK",
		1: "PERDIDO",
		2: "EN_CAMINO",
		3: "ERROR",
	}
	Estatus_value = map[string]int32{
		"OK":        0,
		"PERDIDO":   1,
		"EN_CAMINO": 2,
		"ERROR":     3,
	}
)

func (x Estatus) Enum() *Estatus {
	p := new(Estatus)
	*p = x
	return p
}

func (x Estatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Estatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pedido_pedido_proto_enumTypes[0].Descriptor()
}

func (Estatus) Type() protoreflect.EnumType {
	return &file_pedido_pedido_proto_enumTypes[0]
}

func (x Estatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Estatus.Descriptor instead.
func (Estatus) EnumDescriptor() ([]byte, []int) {
	return file_pedido_pedido_proto_rawDescGZIP(), []int{0}
}

type Producto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID uint32 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *Producto) Reset() {
	*x = Producto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pedido_pedido_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Producto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Producto) ProtoMessage() {}

func (x *Producto) ProtoReflect() protoreflect.Message {
	mi := &file_pedido_pedido_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Producto.ProtoReflect.Descriptor instead.
func (*Producto) Descriptor() ([]byte, []int) {
	return file_pedido_pedido_proto_rawDescGZIP(), []int{0}
}

func (x *Producto) GetID() uint32 {
	if x != nil {
		return x.ID
	}
	return 0
}

type Encargo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TipoLocal      string `protobuf:"bytes,1,opt,name=tipo_local,json=tipoLocal,proto3" json:"tipo_local,omitempty"`
	NombreProducto string `protobuf:"bytes,2,opt,name=nombre_producto,json=nombreProducto,proto3" json:"nombre_producto,omitempty"`
	Valor          uint32 `protobuf:"varint,3,opt,name=valor,proto3" json:"valor,omitempty"`
	Origen         string `protobuf:"bytes,4,opt,name=origen,proto3" json:"origen,omitempty"`
	Destino        string `protobuf:"bytes,5,opt,name=destino,proto3" json:"destino,omitempty"`
}

func (x *Encargo) Reset() {
	*x = Encargo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pedido_pedido_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Encargo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Encargo) ProtoMessage() {}

func (x *Encargo) ProtoReflect() protoreflect.Message {
	mi := &file_pedido_pedido_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Encargo.ProtoReflect.Descriptor instead.
func (*Encargo) Descriptor() ([]byte, []int) {
	return file_pedido_pedido_proto_rawDescGZIP(), []int{1}
}

func (x *Encargo) GetTipoLocal() string {
	if x != nil {
		return x.TipoLocal
	}
	return ""
}

func (x *Encargo) GetNombreProducto() string {
	if x != nil {
		return x.NombreProducto
	}
	return ""
}

func (x *Encargo) GetValor() uint32 {
	if x != nil {
		return x.Valor
	}
	return 0
}

func (x *Encargo) GetOrigen() string {
	if x != nil {
		return x.Origen
	}
	return ""
}

func (x *Encargo) GetDestino() string {
	if x != nil {
		return x.Destino
	}
	return ""
}

var File_pedido_pedido_proto protoreflect.FileDescriptor

var file_pedido_pedido_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x2f, 0x70, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x22, 0x1a, 0x0a,
	0x08, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x49, 0x44, 0x22, 0x99, 0x01, 0x0a, 0x07, 0x45, 0x6e,
	0x63, 0x61, 0x72, 0x67, 0x6f, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x69, 0x70, 0x6f, 0x5f, 0x6c, 0x6f,
	0x63, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x69, 0x70, 0x6f, 0x4c,
	0x6f, 0x63, 0x61, 0x6c, 0x12, 0x27, 0x0a, 0x0f, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x5f, 0x70,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x6e,
	0x6f, 0x6d, 0x62, 0x72, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x6f, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x6f, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x65, 0x6e, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x65, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x64,
	0x65, 0x73, 0x74, 0x69, 0x6e, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x65,
	0x73, 0x74, 0x69, 0x6e, 0x6f, 0x2a, 0x38, 0x0a, 0x07, 0x45, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x45, 0x52, 0x44,
	0x49, 0x44, 0x4f, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x45, 0x4e, 0x5f, 0x43, 0x41, 0x4d, 0x49,
	0x4e, 0x4f, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x03, 0x32,
	0x77, 0x0a, 0x0d, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x61, 0x63, 0x63, 0x69, 0x6f, 0x6e, 0x65, 0x73,
	0x12, 0x2e, 0x0a, 0x08, 0x45, 0x6e, 0x63, 0x61, 0x72, 0x67, 0x61, 0x72, 0x12, 0x0f, 0x2e, 0x70,
	0x65, 0x64, 0x69, 0x64, 0x6f, 0x2e, 0x45, 0x6e, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x1a, 0x0f, 0x2e,
	0x70, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x2e, 0x45, 0x6e, 0x63, 0x61, 0x72, 0x67, 0x6f, 0x22, 0x00,
	0x12, 0x36, 0x0a, 0x0e, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x5f, 0x65, 0x6e, 0x63, 0x61, 0x72,
	0x67, 0x6f, 0x12, 0x10, 0x2e, 0x70, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x2e, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x6f, 0x1a, 0x10, 0x2e, 0x70, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x2e, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x6f, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pedido_pedido_proto_rawDescOnce sync.Once
	file_pedido_pedido_proto_rawDescData = file_pedido_pedido_proto_rawDesc
)

func file_pedido_pedido_proto_rawDescGZIP() []byte {
	file_pedido_pedido_proto_rawDescOnce.Do(func() {
		file_pedido_pedido_proto_rawDescData = protoimpl.X.CompressGZIP(file_pedido_pedido_proto_rawDescData)
	})
	return file_pedido_pedido_proto_rawDescData
}

var file_pedido_pedido_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pedido_pedido_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pedido_pedido_proto_goTypes = []interface{}{
	(Estatus)(0),     // 0: pedido.Estatus
	(*Producto)(nil), // 1: pedido.Producto
	(*Encargo)(nil),  // 2: pedido.Encargo
}
var file_pedido_pedido_proto_depIdxs = []int32{
	2, // 0: pedido.Interacciones.Encargar:input_type -> pedido.Encargo
	1, // 1: pedido.Interacciones.Estado_encargo:input_type -> pedido.Producto
	2, // 2: pedido.Interacciones.Encargar:output_type -> pedido.Encargo
	1, // 3: pedido.Interacciones.Estado_encargo:output_type -> pedido.Producto
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pedido_pedido_proto_init() }
func file_pedido_pedido_proto_init() {
	if File_pedido_pedido_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pedido_pedido_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Producto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pedido_pedido_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Encargo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pedido_pedido_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pedido_pedido_proto_goTypes,
		DependencyIndexes: file_pedido_pedido_proto_depIdxs,
		EnumInfos:         file_pedido_pedido_proto_enumTypes,
		MessageInfos:      file_pedido_pedido_proto_msgTypes,
	}.Build()
	File_pedido_pedido_proto = out.File
	file_pedido_pedido_proto_rawDesc = nil
	file_pedido_pedido_proto_goTypes = nil
	file_pedido_pedido_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// InteraccionesClient is the client API for Interacciones service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type InteraccionesClient interface {
	Encargar(ctx context.Context, in *Encargo, opts ...grpc.CallOption) (*Encargo, error)
	EstadoEncargo(ctx context.Context, in *Producto, opts ...grpc.CallOption) (*Producto, error)
}

type interaccionesClient struct {
	cc grpc.ClientConnInterface
}

func NewInteraccionesClient(cc grpc.ClientConnInterface) InteraccionesClient {
	return &interaccionesClient{cc}
}

func (c *interaccionesClient) Encargar(ctx context.Context, in *Encargo, opts ...grpc.CallOption) (*Encargo, error) {
	out := new(Encargo)
	err := c.cc.Invoke(ctx, "/pedido.Interacciones/Encargar", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interaccionesClient) EstadoEncargo(ctx context.Context, in *Producto, opts ...grpc.CallOption) (*Producto, error) {
	out := new(Producto)
	err := c.cc.Invoke(ctx, "/pedido.Interacciones/Estado_encargo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InteraccionesServer is the server API for Interacciones service.
type InteraccionesServer interface {
	Encargar(context.Context, *Encargo) (*Encargo, error)
	EstadoEncargo(context.Context, *Producto) (*Producto, error)
}

// UnimplementedInteraccionesServer can be embedded to have forward compatible implementations.
type UnimplementedInteraccionesServer struct {
}

func (*UnimplementedInteraccionesServer) Encargar(context.Context, *Encargo) (*Encargo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Encargar not implemented")
}
func (*UnimplementedInteraccionesServer) EstadoEncargo(context.Context, *Producto) (*Producto, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EstadoEncargo not implemented")
}

func RegisterInteraccionesServer(s *grpc.Server, srv InteraccionesServer) {
	s.RegisterService(&_Interacciones_serviceDesc, srv)
}

func _Interacciones_Encargar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Encargo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteraccionesServer).Encargar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pedido.Interacciones/Encargar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteraccionesServer).Encargar(ctx, req.(*Encargo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Interacciones_EstadoEncargo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Producto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteraccionesServer).EstadoEncargo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pedido.Interacciones/EstadoEncargo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteraccionesServer).EstadoEncargo(ctx, req.(*Producto))
	}
	return interceptor(ctx, in, info, handler)
}

var _Interacciones_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pedido.Interacciones",
	HandlerType: (*InteraccionesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Encargar",
			Handler:    _Interacciones_Encargar_Handler,
		},
		{
			MethodName: "Estado_encargo",
			Handler:    _Interacciones_EstadoEncargo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pedido/pedido.proto",
}
